### ISSUE TITLE
Redirect log information to stdout in CI/CD setup

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#402]
As a Sakuli user, I want it to print the log output to stdout instead of the nicely looking - but in CI/CD unusable - cli output.

![image.png](https://images.zenhubusercontent.com/5bd84806d2996a6154b73678/4d809a15-2046-408e-8dc9-5631869e4fe3)

Acceptance criteria:
- [ ] An optional property is added to redirect the log file output to stdout
- [ ] The default of that optional property is: Logging to logfile; CLI output is not changed
- [ ] The property can also be set as environment variable
- [ ] Absence of the environment variable results in the current behavior: Logging to logfile; CLI output is not changed

**Comment by svettwer** [comment]
@ZNicoZ This will be time consuming (at least a 13 in summary) - Should we do that from your opinion?
